apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swazz.fullname" . }}-runner
  labels:
    {{- include "swazz.labels" . | nindent 4 }}
    app.kubernetes.io/component: runner
spec:
  replicas: {{ .Values.runner.replicaCount }}
  selector:
    matchLabels:
      {{- include "swazz.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: runner
  template:
    metadata:
      labels:
        {{- include "swazz.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: runner
    spec:
      containers:
        - name: runner
          image: "{{ .Values.runner.image.repository }}:{{ .Values.runner.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.runner.image.pullPolicy }}
          env:
            - name: COORDINATOR_URL
              value: {{ .Values.runner.env.COORDINATOR_URL | default (printf "ws://%s-edge:%v/api/runners/connect" (include "swazz.fullname" .) .Values.edge.service.port) | quote }}
            {{- range $key, $value := .Values.runner.env }}
            {{- if ne $key "COORDINATOR_URL" }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.runner.resources | nindent 12 }}
      {{- with .Values.runner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runner.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runner.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
