apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swazz.fullname" . }}-secret
  labels:
    {{- include "swazz.labels" . | nindent 4 }}
type: Opaque
data:
  jwtSecret: {{ .Values.global.jwtSecret | b64enc | quote }}
