// Copyright (c) 2026 Swazz Authors
// This file is part of Swazz
// Swazz is licensed under the Business Source License 1.1 (BSL 1.1)
// See the LICENSE file in the project root or visit https://github.com/SecH0us3/swazz for more details

package generator

import (
	"fmt"
	"math/rand/v2"
	"strings"

	"github.com/google/uuid"

	"swazz-engine/internal/generator/payloads"
	"swazz-engine/internal/oob"
	"swazz-engine/internal/sstistore"
	"swazz-engine/internal/swagger"
)

var maliciousStringCategories = []struct {
	category string
	slice    []any
}{
	{payloads.CatMaliciousEncoding, payloads.MaliciousEncoding},
	{payloads.CatMaliciousSQLi, payloads.MaliciousSQLi},
	{payloads.CatMaliciousXSS, payloads.MaliciousXSS},
	{payloads.CatMaliciousPathTraversal, payloads.MaliciousPathTraversal},
	{payloads.CatOOBInteraction, payloads.MaliciousOOB},
	{payloads.CatMaliciousCmdi, payloads.MaliciousCmdi},
	{payloads.CatMaliciousSSTI, payloads.MaliciousSSTI},
	{payloads.CatMaliciousXXE, payloads.MaliciousXXE},
}

func (g *Generator) generateString(format, propName string) any {
	return g.generateStringInternal(format, propName, false)
}

func (g *Generator) generateStringArrayItem(format, propName string) any {
	return g.generateStringInternal(format, propName, true)
}

func (g *Generator) generateStringInternal(format, propName string, inArray bool) any {
	if g.profile == swagger.ProfileRandom {
		return g.fallbackRandom(propName)
	}

	if format == "uuid" {
		return g.generateUUID()
	}

	switch g.profile {
	case swagger.ProfileBoundary:
		if g.isCategoryEnabled(payloads.CatBoundaryStrings) {
			val := seqPick(&g.mu, payloads.BoundaryStrings, &g.bStrIdx)
			if strVal, ok := val.(string); ok {
				maxAllowed := 104_857_600 // 100MB default ceiling
				if inArray {
					maxAllowed = 1024 // 1KB per item in arrays to prevent OOM
				} else if g.settings.MaxPayloadSizeBytes > 0 {
					maxAllowed = g.settings.MaxPayloadSizeBytes
				}
				if len(strVal) > maxAllowed {
					return strVal[:maxAllowed]
				}
				return strVal
			}
			return val
		}
	case swagger.ProfileMalicious:
		if g.hasActiveMaliciousStrings {
			val := seqPick(&g.mu, g.cachedMaliciousStrings, &g.mStrIdx)
			if strVal, ok := val.(string); ok {
				if strings.Contains(strVal, "{{OOB_URL}}") {
					u := uuid.New().String()
					url := g.oobURL(u)

					endpoint := g.Endpoint
					if endpoint == "" {
						endpoint = "Generated by Fuzzer"
					}
					// Register with global store
					oob.GlobalStore.RegisterUUID(u, &oob.OOBContext{
						SessionID: g.RunID,
						Endpoint:  endpoint,
						Payload:   strVal,
					})

					strVal = strings.ReplaceAll(strVal, "{{OOB_URL}}", url)
				}
				if strings.Contains(strVal, "7*7") || strings.Contains(strVal, "7+'7'") {
					strVal = g.randomizeAndRegisterSSTI(strVal)
				}
				if g.settings.SemanticMutationEnabled() && format != "" {
					return g.GenerateSemanticValue(format, strVal)
				}
				return strVal
			}
			return val
		}
	}

	res := g.fallbackRandom(propName)
	if strRes, ok := res.(string); ok && g.settings.SemanticMutationEnabled() && format != "" {
		return g.GenerateSemanticValue(format, strRes)
	}
	return res
}

func (g *Generator) getActiveMaliciousStrings() ([]any, bool) {
	var all []any
	hasAny := false
	for _, item := range maliciousStringCategories {
		if g.isCategoryEnabled(item.category) {
			all = append(all, item.slice...)
			hasAny = true
		}
	}
	if len(all) == 0 {
		return []any{payloads.Word()}, false
	}
	return all, hasAny
}

func (g *Generator) generateDate() any {
	switch g.profile {
	case swagger.ProfileBoundary:
		if g.isCategoryEnabled(payloads.CatBoundaryDates) {
			return seqPick(&g.mu, payloads.BoundaryDates, &g.bDateIdx)
		}
	case swagger.ProfileMalicious:
		if g.isCategoryEnabled(payloads.CatMaliciousDates) {
			return seqPick(&g.mu, payloads.MaliciousDates, &g.mDateIdx)
		}
	}
	return payloads.RandomDate().Format("2006-01-02T15:04:05.000Z")
}

func (g *Generator) generateUUID() any {
	switch g.profile {
	case swagger.ProfileMalicious:
		// Use boundary UUIDs occasionally for "malicious" uuid testing
		if rand.Float64() < 0.1 { // #nosec G404 -- non-security randomness for fuzzer
			return seqPick(&g.mu, payloads.BoundaryUUIDs, &g.mUUIDIdx)
		}
	case swagger.ProfileBoundary:
		if g.isCategoryEnabled(payloads.CatBoundaryUUIDs) {
			// Occasionally test boundary UUIDs
			if rand.Float64() < 0.2 { // #nosec G404 -- non-security randomness for fuzzer
				return seqPick(&g.mu, payloads.BoundaryUUIDs, &g.bUUIDIdx)
			}
		}
	}
	return payloads.UUID()
}

func (g *Generator) fallbackRandom(propName string) any {
	if propName != "" {
		lower := strings.ToLower(propName)
		if strings.Contains(lower, "email") {
			return payloads.Email()
		}
		if strings.Contains(lower, "id") || strings.Contains(lower, "uuid") {
			return payloads.UUID()
		}
		if strings.Contains(lower, "slug") || strings.Contains(lower, "name") {
			return payloads.Word()
		}
		if strings.Contains(lower, "num") || strings.Contains(lower, "count") || strings.Contains(lower, "page") {
			return payloads.IntRange(1, 100)
		}
	}
	return payloads.RandomString(payloads.IntRange(3, 10))
}

func (g *Generator) oobURL(uuidStr string) string {
	baseURL := g.oobServerURL
	if baseURL == "" {
		baseURL = "http://localhost:8080/api/oob"
	} else {
		if !strings.HasPrefix(baseURL, "http://") && !strings.HasPrefix(baseURL, "https://") {
			baseURL = "http://" + baseURL
		}
		if !strings.Contains(baseURL, "/api/oob") {
			baseURL = strings.TrimRight(baseURL, "/") + "/api/oob"
		}
	}
	if g.RunID != "" {
		return fmt.Sprintf("%s/%s/%s", strings.TrimRight(baseURL, "/"), g.RunID, uuidStr)
	}
	return fmt.Sprintf("%s/%s", strings.TrimRight(baseURL, "/"), uuidStr)
}

var sstiPrimes = []int{11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97}

func (g *Generator) randomizeAndRegisterSSTI(s string) string {
	p1 := sstiPrimes[rand.IntN(len(sstiPrimes))] // #nosec G404 -- fuzzer payload generation, crypto/rand not needed
	p2 := sstiPrimes[rand.IntN(len(sstiPrimes))] // #nosec G404 -- fuzzer payload generation, crypto/rand not needed
	for p1 == p2 {
		p2 = sstiPrimes[rand.IntN(len(sstiPrimes))] // #nosec G404 -- fuzzer payload generation, crypto/rand not needed
	}

	var rawExpr string
	var expected string

	if strings.Contains(s, "7*7") {
		if rand.Float64() < 0.5 { // #nosec G404 -- fuzzer payload generation, crypto/rand not needed
			rawExpr = fmt.Sprintf("%d*%d", p1, p2)
			expected = fmt.Sprintf("%d", p1*p2)
		} else {
			rawExpr = fmt.Sprintf("%d+%d", p1, p2)
			expected = fmt.Sprintf("%d", p1+p2)
		}
		newS := strings.ReplaceAll(s, "7*7", rawExpr)
		sstistore.GlobalStore.Register(newS, sstistore.SSTIContext{
			RawExpr:  rawExpr,
			Expected: expected,
		})
		return newS
	} else if strings.Contains(s, "7+'7'") {
		rawExpr = fmt.Sprintf("%d+'%d'", p1, p2)
		expected = fmt.Sprintf("%d%d", p1, p2)
		newS := strings.ReplaceAll(s, "7+'7'", rawExpr)
		sstistore.GlobalStore.Register(newS, sstistore.SSTIContext{
			RawExpr:  rawExpr,
			Expected: expected,
		})
		return newS
	}
	return s
}

// GenerateSemanticValue returns a semantic format-wrapped payload for a given vector.
func (g *Generator) GenerateSemanticValue(format string, vector string) string {
	var variants []string
	switch strings.ToLower(format) {
	case "email":
		variants = WrapEmail(vector)
	case "date", "date-time":
		variants = WrapDateTime(vector)
	case "uri", "url":
		variants = WrapURL(vector)
	case "uuid":
		variants = WrapUUID(vector)
	case "phone", "tel":
		variants = WrapPhone(vector)
	default:
		return vector
	}

	if len(variants) == 0 {
		return vector
	}
	return variants[rand.IntN(len(variants))] // #nosec G404 -- fuzzer payload rotation
}
