title: Swazz
description: A Smart API Fuzzer designed to identify crashes, logic flaws, and security vulnerabilities by parsing Swagger/OpenAPI specifications.
theme: jekyll-theme-minimal
url: ""
search_enabled: true
plugins:
  - jekyll-seo-tag
